<?php

/**
* @file
* A description of what your module does.
*/
function omdb_views_data() {
    $data = [];
    $data['omdb_profile']['table']['group'] = t('omdb profile');
    $data['omdb_profile']['table']['base'] = [
        'title' => t('Omdb profile'),
        'help' => t('Omdb profile data provided by the Fitbit API\'s User Profile endpoint.'),
        'query_id' => 'omdb',
    ];

    $data['omdb_profile']['title'] = [
      'title' => t('Title'),
      'help' => t('OMDb users\' display name.'),
      'field' => [
        'id' => 'omdb_title',
      ],
    ];

    $data['omdb_profile']['id'] = [
      'title' => t('Id'),
      'help' => t('Same id'),
      'field' => [
        'id' => 'api_id',
      ],
      'argument' => [
        'id' => 'api_id_argument'
      ]
    ];

    $data['omdb_profile']['name'] = [
      'title' => t('Name'),
      'help' => t('Name:'),
      'field' => [
        'id' => 'api_name',
      ],
      'argument' => [
        'id' => 'api_name_argument'
      ]
    ];

    $data['omdb_profile']['page'] = [
      'title' => t('Page'),
      'help' => t('Page'),
      'field' => [
        'id' => 'api_page',
      ],
    ];
  return $data;
}

///**
// * Implements hook_views_data_alter().
// */
//function omdb_views_data_alter(array &$data) {
//  dsm($data);
//}
